PACKAGE_NAME="yoga-s740-vpc-poll"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="yoga_s740_vpc_poll"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make clean KERNELRELEASE=${kernelver}"

AUTOINSTALL="yes"
